name: Personal-Blog-API PROD Test

on:
  workflow_dispatch:

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install dependencies
        run:  npm ci 

      - name: Run linter
        run:  npm run lint

  types: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install dependencies
        run:  npm ci 

      - name: Run typescript
        run:  npm run ts-check

  unit-test: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install dependencies
        run:  npm ci 

      - name: Run unit test
        run:  npm run test:unit
  
  integration-test: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install dependencies
        run:  npm ci 

      - name: Run integration tests
        run:  npm run test:integration      